### ISSUE TITLE
Documentation & plunker demo

### ISSUE THREAD

**Issue by nkdweb** [Jaspero/ng2-alerts#13]
Hi,

I request you to please provide proper simple documentation from installation to working alerts. 

> In https://jaspero.co/resources/projects/ng-alerts, steps are given like this

```
An easy to use alert library for Angular 2.
 npm install --save @jaspero/ng2-alerts
```

> In github it shows like

`$ npm install --save @jaspero/ng-alerts`

It is confusing what to install and I'm lost. Please describe for end to end working functionality and it will be great if we have plunker or jsfiddle working demo of the ng-alerts.

Thanks,
Dinesh

**Comment by rahul-krish** [comment]
Me too.. and couldn't find out what i am doing wrong. Alert doesn't show up

**Comment by makiJS** [comment]
New demo https://stackblitz.com/edit/jaspero-ng-alerts-example
