### ISSUE TITLE
NullInjectorError: No provider for AlertsService!

### ISSUE THREAD

**Issue by nkdweb** [Jaspero/ng2-alerts#14]
I have setup ng-alerts as per documentation in github.

After setup, When i try to run the application, Im getting this error which is attached as image. Please check it and let me know how to fix this issue.

![provider](https://user-images.githubusercontent.com/2375291/35143608-0f11ad6e-fd28-11e7-9019-d4e841fcd5f5.JPG)

**Comment by makiJS** [comment]
Here is a new example.
https://stackblitz.com/edit/jaspero-ng-alerts-example
