### ISSUE TITLE
Running npm install --save @jaspero/ng2-alerts issue

### ISSUE THREAD

**Issue by gags88** [Jaspero/ng2-alerts#2]
Hi,

After doing npm install on your package, 

dist/index.d.ts has below code

    export * from './src/alert.component';
    export * from './src/alerts.component';
    export * from './src/alerts.service';
    export * from './src/interfaces/alert-emit';
    export * from './src/interfaces/alert-settings';
    export * from './src/interfaces/alert-type';
    export declare class JasperoAlertsModule {
    }

and when i run ng serve then i get an error

`ERROR in JasperoAlertsModule is not an NgModule`

When i manually go edit this file and add @NgModule({}) decorator then everything works fine.
May be you can consider updating ?

**Comment by flauc** [comment]
Hi @gags88 

Where are you importing the library from?

It should be: `import {JasperoAlertsModule} from '@jaspero/ng2-alerts';`

**Comment by gags88** [comment]
That was the mistake.. i did it from '@jaspero/ng2-alerts/dist'
