### ISSUE TITLE
 ERROR in JasperoAlertsModule is not an NgModule

### ISSUE THREAD

**Issue by fizdalf** [Jaspero/ng2-alerts#3]
Steps to reproduce 

create a new app 
`ng new jasperoApp`

install jaspero/ng2-alerts.
install angular/animation.

import JasperoAlertsModule in app.module.ts

run `ng build`

**Comment by flauc** [comment]
Hi @fizdalf 
Is this how you imported the module?
```
import {JasperoAlertsModule} from '@jaspero/ng2-alerts';
```

**Comment by Hesesses** [comment]
the import line should be documented somewhere
