### ISSUE TITLE
Custom Title

### ISSUE THREAD

**Issue by danielvaldebenito** [Jaspero/ng2-alerts#4]
Thank you for your work. 
A question: It's possible to display a personalized title (replacing 'Success', 'Error', etc)?

**Comment by flauc** [comment]
Hi @danielvaldebenito,

No, sadly it isn't at the moment. You are right though, we should implement it. 
I will try to implement it as soon as possible. 
Thanks for the suggestion 👍

**Comment by motiejunas** [comment]
That's sad. Really nice component, but couldn't use it without an ability to translate titles...

**Comment by flauc** [comment]
@danielvaldebenito and @motiejunas I'm sorry for the long wait, this is finally implemented you can now pass in the title that can be a string an html string (it will get parsed to SafeHtml) or even a TemplateRef.
