### ISSUE TITLE
Alert Appears to be running twice

### ISSUE THREAD

**Issue by kyledef** [Jaspero/ng2-alerts#6]
The demo as well as my initial implementation based on documentation seems to be running twice upon launch. I'm unsure if this is the desired behaviour, but seems like a bug to me.

**Comment by flauc** [comment]
Hi @kyledef 

I think you might be missing (and me on the live site 👎 ) the `.forRoot()` method. I will test and let you know if it fixed it for me.

**Comment by flauc** [comment]
This is working for me, is it working for you?
