### ISSUE TITLE
Can't find this package on npmjs.com

### ISSUE THREAD

**Issue by nauxliu** [Jaspero/ng2-alerts#7]
How to upgrade to 1.0 ?

**Comment by flauc** [comment]
Hi @NauxLiu ,

Hmm, It's definitely there. 

https://www.npmjs.com/package/@jaspero/ng-alerts

`npm i @jaspero/ng-alerts` this doesn't work for you?

**Comment by flauc** [comment]
Feel free to reopen if you are still having this issue.
